### ISSUE TITLE
1.2.2 seems to use significantly consume more memory than 1.2.0

### ISSUE THREAD

**Issue by 030** [osixia/docker-openldap#259] opened 2018-10-31 15:53 UTC
A max memory limit of 128MB was enough to run 1.2.0, but 1.2.2 gets OOM killed when the same memory limits are applied.

**Comment by 030** [comment] 2018-10-31 18:04
I had to configure 1GB to avoid an OOM kill

**Comment by naanselmo** [comment] 2018-10-31 18:18
Essentially a duplicate of #242

**Closed** 2018-11-02 22:53 UTC
